version: "3.9"

services:
  db:
    image: postgres:16
    restart: unless-stopped
    env_file: .env
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  app:
    build: .
    command: python -m app.main
    depends_on:
      - db
    volumes:
      - .:/code
    working_dir: /code
    env_file: .env
    environment:
      - DATABASE_URL=postgresql+psycopg2://$POSTGRES_USER:$POSTGRES_PASSWORD@db:5432/$POSTGRES_DB

volumes:
  db_data:
